SKU = [
    ('ford_s_s_003', 'Ford Mustang outline, Car silhouette, Wall decor, Wall art, Gift for him, Gift for her, Birthday gift, Birthday present, 3D print car'),
    ('bmw_s_s_001', 'BMW M3 outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('nissan_s_s_001', 'Nissan 240sx (small) outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('porsche_s_s_001', 'Porsche 930 Turbo outline, Porsche 911, Car silhouette, Wall art, Fan art, Office decor, 3D print car'),
    ('audi_s_s_001', 'Audi Sport Quattro outline, Car silhouette, Home decor, Room decor aesthetic, Car gift, Gift for him, Gift for her, Birthday gift for him'),
    ('mazda_s_s_001', 'Mazda Miata MX5 outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('honda_s_s_001', 'Honda S2000 outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('scion_s_s_001', 'Scion FRS outline, Car silhouette, Home decor, Room decor aesthetic, Car gift, Gift for him, Gift for her, Birthday gift for him'),
    ('bmw_s_d_002', 'BMW M4 Outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('ford_s_d_001', 'Ford Focus RS outline (small), Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('nissan_s_d_002', 'Nissan 370Z outline, Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Gift for car enthusiast'),
    ('ford_s_d_002', 'Ford Mustang outline (small), Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('nissan_l_s_001', 'Nissan 240sx (large) outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('ford_l_d_001', 'Ford Focus RS outline (large), Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('ford_l_d_002', 'Ford Mustang outline (large), Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('custom_001', 'Custom 3D Printed Car Silhouette, Car outline, dream car gift, wall decor, fan art, custom order'),
    ('ford_n_d_001', 'Ford Focus RS Neon Outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_n_s_001', 'Subie Sedan Neon Outline, for Subaru fans, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_n_s_002', 'Subie Hatchback Neon Outline, for Subaru fans, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_s_s_001', 'Subaru WRX outline, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift, 3D print car'),
    ('subie_s_s_002', 'Subaru Impreza 22b outline, Car silhouette, Home decor, Room decor aesthetic, Car gift, Gift for him, Gift for her, Birthday gift for him'),
    ('subie_s_s_003', '2015+ Subaru WRX outline, Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_s_d_001', '2015+ Subaru WRX STI outline, Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_s_d_002', 'Subaru WRX STI Hatchback Outline, Car silhouette, Wall decor, Wall art, Desk ornament, Car gift, Gift for him, Gift for her, Birthday gift'),
    ('subie_n_s_003', 'Subaru STI Sedan Neon Outline, for Subaru fans, Car silhouette, Wall decor, Wall art, Car gift, Gift for him, Gift for her, Birthday gift')
]